name: ci-windows

on: [push, pull_request]

jobs:
  ci-windows:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        php:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, openssl, mbstring, json
          coverage: none
          tools: composer:v2

      - name: Show PHP info
        run: |
          php -v
          php -m
          php --ri curl

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run tests
        run: composer test

      - name: Print server logs (on failure)
        if: failure()
        run: php .github/print-logs.php
