name: ci

on: [push, pull_request]

jobs:
  ci-only-curl:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php: ["7.0", "7.1"]

    env:
      PHP_DOCKER_VERSION: ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v2

      - name: prepare
        run: |
          ./.github/prepare-test.sh php

      - name: test
        run: docker exec php composer test

      - name: Print logs
        if: failure()
        run: |
          echo "Http"
          cat tests/server/Http/log.log
          echo "Http2"
          cat tests/server/Http2/log.log
          echo "WebSocket"
          cat tests/server/WebSocket/log.log

  ci-curl-swoole:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        swoole:
          [
            5.1-php8.0,
            5.1-php8.1,
            5.1-php8.2,
            5.0-php8.0,
            5.0-php8.1,
            5.0-php8.2,
            4.8-php7.2,
            4.8-php7.3,
            4.8-php7.4,
            4.8-php8.0,
            4.8-php8.1,
          ]

    env:
      SWOOLE_DOCKER_VERSION: ${{ matrix.swoole }}

    steps:
      - uses: actions/checkout@v2

      - name: prepare
        run: |
          ./.github/prepare-test.sh swoole

      - name: test
        run: docker exec swoole composer test

      - name: Print logs
        if: failure()
        run: |
          echo "Http"
          cat tests/server/Http/log.log
          echo "Http2"
          cat tests/server/Http2/log.log
          echo "WebSocket"
          cat tests/server/WebSocket/log.log
