name: Coding Standards

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        swoole: [5.0-php8.2]

    env:
      SWOOLE_DOCKER_VERSION: ${{ matrix.swoole }}

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          ./.github/prepare-test.sh swoole
          docker exec swoole composer require php-cs-fixer/shim:~3.35.0 --dev

      - name: Test
        run: docker exec swoole ./vendor/bin/php-cs-fixer fix --dry-run --diff
