name: Static Code Analysis

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        swoole: [4.6-php7.4]

    env:
      SWOOLE_DOCKER_VERSION: ${{ matrix.swoole }}

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          ./.github/prepare-test.sh swoole
          docker exec swoole composer require phpstan/phpstan:^0.12.91 --dev

      - name: Test
        run: docker exec swoole ./vendor/bin/phpstan analyse --memory-limit 1G
